### ISSUE TITLE
Unable to connect to KiCAD on Linux (socket not being created)

### ISSUE THREAD

**Issue by Pegoku** [hackclub/kicad-wakatime#10]
OS: Linux (Arch)

Magic word: dreadnought

I have Kicad 8.99 installed with Kicad API enabled

But I'm getting this error:
```
21:03:12 [ERROR] kicad_wakatime                  : Could not connect to KiCAD!
21:03:12 [ERROR] kicad_wakatime                  : Please ensure you are running KiCAD 8.99, and the KiCAD API is enabled
21:03:12 [ERROR] kicad_wakatime                  : (Settings -> Plugins -> Enable KiCAD API)
```

I tried rebooting, but I'm still getting the same error.

![Image](https://github.com/user-attachments/assets/e0c5db61-f648-4e2b-ad8f-5d4a86fcd1e8)
![Image](https://github.com/user-attachments/assets/f4e12341-d3c9-451b-8cc1-88df4ad1ff9a)

**Comment by Pegoku** [comment]
It seems the problem is the api.sock file not being created
`'/tmp/kicad/api.sock': No such file or directory`

**Comment by sporeball** [comment]
the api.sock file is deleted when KiCAD is closed, but does it also say `No such file or directory` even when KiCAD is open?

**Comment by Pegoku** [comment]
Yes, same error with kicad open

**Comment by sporeball** [comment]
as discussed, i don't think this can be solved with a custom socket path because of limitations on the C++ side. adding "help wanted" in case others have any idea what to do.

**Comment by sporeball** [comment]
moved to 0.2.0 milestone; by the time this issue is closed, kicad-wakatime will no longer use the KiCAD API at all anyway.

**Comment by Pegoku** [comment]
Seems to be fixed on latest Kicad build
