### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by sporeball** [hackclub/kicad-wakatime#3]
@24c02 just left kicad-wakatime open for the day and didn't think anything of it until it was found to be using 11.6GB of memory.\
this is really bad! this should be fixed as soon as possible.

**Comment by sporeball** [comment]
this is potentially an issue in fltk's font rendering code (cf. [here](https://stackoverflow.com/questions/68804858/do-i-have-to-delete-pointers-to-widgets-in-fltk) and [here](https://devrant.com/rants/5974349/actually-kinda-sad-that-there-is-no-pure-rust-ui-framework-out-there-but-rather)).

**Comment by sporeball** [comment]
when the egui code from the [0.1.0 branch](https://github.com/hackclub/kicad-wakatime/tree/0.1.0) reaches stable - aiming for sometime before December 12 - i believe the memory leak will be fixed.

**Comment by sporeball** [comment]
pushing back to 0.2.0 milestone; we'll see if removing dependence on the KiCAD API will make this a little better.

**Comment by sporeball** [comment]
using Xcode's Instruments tool on macOS, i've finally isolated the memory leak to the **active-win-pos-rs** crate, which is used to determine whether KiCAD's schematic editor or PCB editor are being used.\
i'll see if i can cut back what it's doing to a form that doesn't leak so much.

**Comment by 24c02** [comment]
lol it's always the ones you least suspect

**Comment by sporeball** [comment]
active-win-pos-rs 0.8.4 will be used in kicad-wakatime 0.1.2 today. closing as fixed.
